Opening commit :construction:
OpenSourcePolitics/decidim pull request #1108
Opened 2021-02-26 09:55 UTC by armandfardeau

#### :tophat: What? Why?

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [ ] If there's a new public field, add it to GraphQL API
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
![Description](URL)

2021-03-01 08:34 UTC, paulinebessoles requested changes
Thanks @armandfardeau ! 
I just see something that needs to be fixed: when I select "My initiatives" the sorting dropdown is displaying all the sorting options (see screenshot below).

<img width="1250" alt="Capture d’écran 2021-03-01 à 09 29 41" src="https://user-images.githubusercontent.com/52420208/109471489-1d83c480-7a71-11eb-8a4c-78133186b30b.png">

When selected, the dropdown display all sorting options.

Could you take a look at this?

2021-03-02 11:00 UTC, paulinebessoles commented
I've investigated further and I encounter a bug in these 2 use cases:
- when running this decidim branch
- when running alt/ppan with this decidim branch (for decidim and decidim-initiatives)

When running alt/ppan, I find the bug on the display of sorting options and I can see other users unpublished initiatives.

When running this decidim branch, the "My initiatives" button is working properly and redirecting me to this URL:
http://localhost:3000/initiatives?filter%5Bsearch_text%5D=&filter%5Bstate%5D%5B%5D=&filter%5Barea_id%5D=&filter%5Bcustom_state%5D%5B%5D=&filter%5Bauthor%5D=&filter%5Bauthor%5D=myself&filter%5Bscope_id%5D%5B%5D=&filter%5Btype_id%5D%5B%5D=

But when I create an initiative, and at the last step of the wizard, I click on "Go to my initiatives", I get the same bug on the display of sorting options (with the URL http://localhost:3000/initiatives?filter%5Bauthor%5D=myself&filter%5Bstate%5D=). 
But I can't see other users unpublished initiatives. 

The behaviour is really weird, and I wonder if it's not caused by an override in alt/ppan. 

I'm available to discuss it in the afternoon if needed 🙂

2021-03-02 11:35 UTC, paulinebessoles commented
It seems that the bug on the display of other users unpublished initiatives is anterior to this PR, as it's on https://ppan-dev.opensourcepolitics.net/. It probably originated in https://github.com/OpenSourcePolitics/decidim/pull/1092

2021-03-09 13:49 UTC, paulinebessoles approved these changes
Tested and approved by product! Thanks @Quentinchampenois

2021-03-09 13:49 UTC, armandfardeau commented on decidim-initiatives/app/assets/javascripts/decidim/initiatives/sort_initiatives.js.es6
> +      return;
Prefer an if/else to a switch case when there is only 2 options.

2021-03-09 13:49 UTC, armandfardeau commented on decidim-initiatives/app/views/decidim/initiatives/initiatives/_filters.html.erb
> +      <%= javascript_include_tag "decidim/initiatives/sort_initiatives" %>
Add include tag at the bottom of the view.

2021-03-09 14:02 UTC, Quentinchampenois commented on decidim-initiatives/app/assets/javascripts/decidim/initiatives/sort_initiatives.js.es6
> +      return;
Thanks for the feedback, I update it

2021-03-09 14:04 UTC, Quentinchampenois commented on decidim-initiatives/app/views/decidim/initiatives/initiatives/_filters.html.erb
> +      <%= javascript_include_tag "decidim/initiatives/sort_initiatives" %>
I have considered to add the tag at the bottom of the view, however, this script is useful only if user is logged. 
Otherwise it will always be loaded.

Should we load it at the bottom of the view anyway @armandfardeau  ?

2021-03-09 14:08 UTC, armandfardeau commented on decidim-initiatives/app/views/decidim/initiatives/initiatives/_filters.html.erb
> +      <%= javascript_include_tag "decidim/initiatives/sort_initiatives" %>
Forget it; Keep up with the way that you described

2021-03-11 14:30 UTC, armandfardeau commented
Is this good to go?

2021-03-11 17:01 UTC, Quentinchampenois commented
> Is this good to go?

Yes !

2021-03-11 17:02 UTC, merged