add request url to cache entry
OpenSourcePolitics/decidim pull request #1144
Opened 2021-06-07 16:21 UTC by Quentinchampenois

#### :tophat: What? Why?

Filter caching seems to be broken when accessing initiatives view from url.

2021-06-07 16:27 UTC, armandfardeau commented
Hi @Quentinchampenois may you check if this error is present on BCN repo? Also I suggest to map around cache version

2021-06-07 16:38 UTC, Quentinchampenois commented
Hi @armandfardeau, 

BCN doesn't seems to be concerned by this behaviour because there is no caching on filters [cf](https://github.com/decidim/decidim/blob/develop/decidim-core/app/views/decidim/shared/_check_boxes_tree.html.erb) 

I will check for the cache version

2021-06-08 13:24 UTC, armandfardeau requested changes

2021-06-08 13:24 UTC, armandfardeau commented on decidim-core/app/views/decidim/shared/_check_boxes_tree.html.erb
> +<% cache "check_boxes_tree/#{Digest::MD5.hexdigest(collection.to_s + request.url)}" do %>
Maybe this is cleaner?

```suggestion
<% cache "check_boxes_tree/#{Digest::MD5.hexdigest(collection.map(&:cache_version) + request.url)}" do %>
```

It would be great if we add some test to spot a future regression.

2021-06-08 13:24 UTC, armandfardeau commented on decidim-core/app/helpers/decidim/caching_helper.rb
> +      end
Aren't you supposed to just generate a hash? It seems that your are overpassing the method responsibility.

Also, I would use two parameters, name and options.
Use the name for the cache_key and use options as a hash directly.

2021-06-08 13:33 UTC, Quentinchampenois commented on decidim-core/app/helpers/decidim/caching_helper.rb
> +      end
Yes it would be cleaner if I defined "name" as a single parameter.

This block just check for the cache_key, if it doesn't exist, it stores the string returned in block and return the value.
The aim of this helper is to return a cache_key as String.

2021-06-11 10:00 UTC, paulinebessoles approved these changes

2021-06-14 15:58 UTC, armandfardeau approved these changes

2021-06-14 16:00 UTC, merged