Feature/pseudomysation
OpenSourcePolitics/decidim pull request #1155
Opened 2021-08-06 10:36 UTC by armandfardeau

2021-08-11 16:16 UTC, paulinebessoles commented on decidim-admin/app/helpers/decidim/admin/application_helper.rb
> +      end
Hi @armandfardeau! When I test, the status is never completed and blocks at 3/20 or 4/19 for example. I think that the total counter might take into account Official proposals (which are not pseudomized) so the task never is completed, and the component can still be edited. 

What do you think?

2021-08-11 16:19 UTC, paulinebessoles commented
@virgile-dev coul'd you tell me what was decided with respect to the users profiles. 
Some of the pseudomized contents are displayed in user's activity, timeline or follow section, should we keep this behaviour?

2021-08-13 14:39 UTC, armandfardeau commented on decidim-admin/app/helpers/decidim/admin/application_helper.rb
> +      end
Currently we take into account the official proposal and we do nothing on it.
I think that we may have another issue.

2021-09-13 16:48 UTC, paulinebessoles commented on decidim-admin/app/helpers/decidim/admin/application_helper.rb
> +      end
I still have the status counter problem: the pseudomize task never really ends (no notification is sent and the counter still says "in progress"). 

<img width="275" alt="Capture d’écran 2021-09-13 à 18 40 26" src="https://user-images.githubusercontent.com/52420208/133124356-f62495d4-7c75-45a1-8ec6-b02809739bda.png">

I find this error in the logs, could this be related to my environment? 

<img width="1414" alt="Capture d’écran 2021-09-13 à 15 57 43" src="https://user-images.githubusercontent.com/52420208/133124413-a445c0a3-c715-4840-8f39-8d33f96b74b0.png">

2021-09-14 09:12 UTC, Quentinchampenois commented on decidim-admin/app/helpers/decidim/admin/application_helper.rb
> +      end
Hi @paulinebessoles, 

You probably have an issue with concurrent transactions, I found a [temporary solution](https://github.com/Shopify/bootsnap/issues/119#issuecomment-446956066) on the Shopify repository. 
I can't assure you that this will solve your problem

2021-09-14 09:20 UTC, Quentinchampenois approved these changes
Nice work ! 

I added some suggestions, but no changes required

2021-09-14 09:20 UTC, Quentinchampenois commented on decidim-admin/app/mailers/decidim/admin/pseudomize_mailer.rb
> +      def notify_admin(user)
It could be easier to read if we expect `admin` as parameter for `notify_admin`

```suggestion
      def notify_admin(admin)
```

2021-09-14 09:20 UTC, Quentinchampenois commented on decidim-admin/spec/mailers/decidim/admin/pseudomize_mailer_spec.rb
> +require "zip"
Is `zip` used here ?

2021-09-14 10:07 UTC, Quentinchampenois commented on decidim-admin/app/helpers/decidim/admin/application_helper.rb
> +      end
I confirm that on my environment, process is blocked at 4/19. And I didn't received notification

2021-09-14 10:08 UTC, Quentinchampenois requested changes
The process never end and block at 4 / 19

2021-09-15 10:33 UTC, paulinebessoles commented on decidim-admin/app/helpers/decidim/admin/application_helper.rb
> +      end
This is confirmed by Sidekiq on https://cndp.osp.dev/ 
<img width="1200" alt="Capture d’écran 2021-09-15 à 12 31 23" src="https://user-images.githubusercontent.com/52420208/133418041-0d9c619a-25e3-41b1-ac66-1496c00f7d5d.png">

2021-09-20 15:07 UTC, armandfardeau commented on decidim-admin/spec/mailers/decidim/admin/pseudomize_mailer_spec.rb
> +require "zip"
```suggestion
```

2021-09-23 17:06 UTC, Quentinchampenois approved these changes

2021-09-24 12:59 UTC, paulinebessoles approved these changes

2021-09-24 12:59 UTC, merged