Fix(rgaa): Nav attributes and aria-current for accessibility compliance
OpenSourcePolitics/decidim pull request #1239
Opened 2024-12-17 14:44 UTC by BarbaraOliveira13

#### :tophat: What? 
Two parts:
1. Added dynamic aria-label attributes to navigation menus to provide better context for screen readers, improving compliance with WCAG [1.3.1 - Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)(Level A).
2. Added aria-current="true" to correctly mark active links within navigation menus, addressing WCAG [2.4.8 - Location](https://www.w3.org/WAI/WCAG21/Understanding/location.html) (Level AAA).

#### :tophat: Why?
This issue originates from an accessibility audit funded by the city of Lyon, targeting compliance with RGAA and corresponding WCAG standards. The changes ensure clearer navigation and improved usability for assistive technologies.

#### :pushpin: Related Issues
- Related to: WCAG 1.3.1, 2.4.8, and RGAA 9.2/10.9.
- Fixes #?

#### :clipboard: Subtasks
- [x] Update <nav> tags to include dynamic aria-label attributes, addressing WCAG [1.3.1 - Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html).
- [x]  Add aria-current="true" to active links in navigation menus to comply with WCAG [2.4.8 - Location](https://www.w3.org/WAI/WCAG21/Understanding/location.html).
- [x] Verify the changes comply with RGAA best practices.
- [ ] Add `CHANGELOG` entry
- [ ] If there's a new public field, add it to GraphQL API
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
<img width="1187" alt="Capture d’écran 2024-12-18 à 17 16 17" src="https://github.com/user-attachments/assets/d57a60d0-1c18-44f5-97d1-d7b7132f869b" />

2024-12-18 10:23 UTC, Quentinchampenois requested changes
The aria-label must be translated in locales files, in English only

2024-12-18 10:23 UTC, Quentinchampenois commented on decidim-core/app/views/decidim/pages/_tabbed.html.erb
> +    <nav role="navigation" aria-label="Sous menu - <%= translated_attribute(page.title) %>">
```suggestion
    <nav role="navigation" aria-label="<%= i18n.t(".navigation.aria_label", title: translated_attribute(page.title)) %>">
```

2024-12-18 10:24 UTC, Quentinchampenois commented on decidim-core/app/views/decidim/pages/_tabbed.html.erb
> +    <nav role="navigation" aria-label="Sous menu - <%= translated_attribute(page.title) %>">
Translation key could just be `aria_label`

2024-12-18 16:44 UTC, BarbaraOliveira13 commented on decidim-core/app/views/decidim/pages/_tabbed.html.erb
> +    <nav role="navigation" aria-label="Sous menu - <%= translated_attribute(page.title) %>">
thanks, changes made 👍

2024-12-19 11:02 UTC, Quentinchampenois requested changes

2024-12-19 11:02 UTC, Quentinchampenois commented on decidim-core/app/views/decidim/pages/_tabbed.html.erb
> +            <%= link_to translated_attribute(sibling.title), page_path(sibling.slug), aria_current: ("true"if page == sibling) %>
```suggestion
            <%= link_to translated_attribute(sibling.title), page_path(sibling.slug), aria_current: (page == sibling).to_s %>
```

2024-12-19 11:02 UTC, Quentinchampenois commented on decidim-core/app/views/decidim/pages/_tabbed.html.erb
> +            <%= link_to translated_attribute(sibling.title), page_path(sibling.slug), aria_current: ("true"if page == sibling) %>
Condition in itself returns a TrueClass or FalseClass, you can use the condition return as string directly

2024-12-19 16:31 UTC, BarbaraOliveira13 commented on decidim-core/app/views/decidim/pages/_tabbed.html.erb
> +            <%= link_to translated_attribute(sibling.title), page_path(sibling.slug), aria_current: ("true"if page == sibling) %>
Indeed, thanks!

2024-12-23 09:30 UTC, Quentinchampenois approved these changes

2025-10-22 07:47 UTC, closed without merging