fix wcag search filters navigation
OpenSourcePolitics/decidim pull request #1240
Opened 2024-12-20 17:34 UTC by BarbaraOliveira13

#### :tophat: What? Why?

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [ ] If there's a new public field, add it to GraphQL API
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
![Description](URL)

2024-12-23 15:37 UTC, AyakorK approved these changes
The changes look great to me, well done!

I do have a small point of consideration regarding the third line of `_filters.html.erb`, specifically the default value. It may not be strictly necessary, but it seems like a good safeguard against potential errors.

2024-12-27 11:31 UTC, BarbaraOliveira13 commented
> The changes look great to me, well done!
> 
> I do have a small point of consideration regarding the third line of `_filters.html.erb`, specifically the default value. It may not be strictly necessary, but it seems like a good safeguard against potential errors.

Thanks for the feedback! I agree that the default: "Search filters" parameter might not always be necessary if the key decidim.searches.filters.title is always present. Do you think it’s better to keep it as a safeguard or remove it for simplicity, @Quentinchampenois ?

2025-01-09 09:37 UTC, Quentinchampenois requested changes
It's hard for me to understand changes, 

The `nav` tag seems good with the right role and the `aria-labelledby`. However the value of `aria-labelledby` should match the ID of the currently existing H1 title (cf: [32 Results for the search: "" ](https://decidim-029.osp.dev/search?term=)

We shall not create a new h1 tag but add an ID to the existing H1 to match it

2025-01-09 09:37 UTC, Quentinchampenois commented on decidim-core/app/views/decidim/searches/_filters.html.erb
> +    <%= t("decidim.searches.filters.title", default: "Search filters") %>
I agree, the default parameter is not necessary in this case

```suggestion
    <%= t("decidim.searches.filters.title") %>
```

2025-01-10 15:10 UTC, BarbaraOliveira13 commented on decidim-core/app/views/decidim/searches/_filters.html.erb
> +    <%= t("decidim.searches.filters.title", default: "Search filters") %>
Good point! The changes have been implemented for better dynamic approach

2025-01-13 15:11 UTC, BarbaraOliveira13 commented
> It's hard for me to understand changes,
> 
> The `nav` tag seems good with the right role and the `aria-labelledby`. However the value of `aria-labelledby` should match the ID of the currently existing H1 title (cf: [32 Results for the search: "" ](https://decidim-029.osp.dev/search?term=))
> 
> We shall not create a new h1 tag but add an ID to the existing H1 to match it

@Quentinchampenois 
Sorry! I overlooked the H1 review. I have deleted the additional H1 and update the `aria-labelledby` attribute to refer the ID of the existing H1. 
Hope is better :)

2025-01-22 14:38 UTC, Quentinchampenois approved these changes

2025-01-28 13:28 UTC, Quentinchampenois approved these changes

2025-02-19 15:24 UTC, closed without merging